// This file will be processed by the MIDL tool to
// produce the type library (FcApi.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(9C56F46A-B80A-4FC9-AF98-3182C7CFFDF5),
	dual,
	nonextensible,
	pointer_default(unique),
]
interface IFreeComposeController: IDispatch {
};

[
	uuid(52AE64DA-58B6-42B4-8171-18A78E837931),
	version(1.0),
]
library FcApiLib
{
	importlib("stdole2.tlb");
	[
		uuid(A0509518-58D8-4D74-9CF4-5BB942FBC542)		
	]
	coclass FreeComposeController
	{
		[default] interface IFreeComposeController;
	};
};
